version: "3"
x-data:
  common: &common
    restart: unless-stopped
    env_file: [.env]
    network_mode: host
    environment:
    - "HAPROXY_S_HELPERS_PORT=${HAPROXY_S_HELPERS_PORT:-65008}"
    - "HAPROXY_S_HAPROXY_PORT=${HAPROXY_S_HAPROXY_PORT:-65009}"
    - "HAPROXY_S_CERTBOT_PORT=${HAPROXY_S_CERTBOT_PORT:-65010}"
    - "HAPROXY_LISTEN_IP=${HAPROXY_LISTEN_IP:-0.0.0.0}"
    - "HAPROXY_LISTEN_INT_IP=${HAPROXY_LISTEN_INT_IP:-127.0.0.1}"
    - "HAPROXY_LISTEN_PORT=${HAPROXY_LISTEN_PORT:-80}"
    - "HAPROXY_LISTEN_SPORT=${HAPROXY_LISTEN_SPORT:-443}"
    - "HAPROXY_LISTEN_CPORT=${HAPROXY_LISTEN_CPORT:-9999}"
    - "HAPROXY_REDIR_HOST=${HAPROXY_REDIR_HOST:-127.0.0.1}"
    - "HAPROXY_REDIR_PORT=${HAPROXY_REDIR_PORT:-8080}"
    - "HAPROXY_CERTBOT_ADDRESS=${HAPROXY_CERTBOT_ADDRESS:-127.0.0.1}"
    - "SCERT=/certificates/self.crt"
    volumes:
    - ./haproxy:/haproxy:ro
    - ./certificates:/certificates
    - cops_helpers:/cops
services:
  helpers:
    <<: [ *common ]
    image: corpusops/debian-bare:buster
    command:
    - sh
    - "-exc"
    - |-
      : helpers
      for i in /cops_helpers/* /bin/busybox;do
        rm -f /cops/$$(basename $$i)
        cp -arfv $$(readlink -f $$i) /cops/$$(basename $$i)
      done
      : selfsigned startup cert
      if [ ! -e $$SCERT ];then
        openssl req -batch -nodes -x509 -newkey rsa:2048 -keyout k -out c -days 30000 -subj "/C=FR/CN=selfsigned/"
        cat k c>$$SCERT
      fi
      while true;do printf "HTTP/1.1 200 OK\n\nstarted"| ( busybox nc -l 127.0.0.1 -p ${HAPROXY_S_HELPERS_PORT:-65008}||/bin/true);done
  haproxy:
    <<: [ *common ]
    image: "{{cops_drupal_haproxy_image}}"
    user: root
    depends_on: [helpers]
    restart: always
    entrypoint:
    - "bash"
    - "-exc"
    - |-
      export PATH="/cops:$$PATH";while :;do if ( dockerize -wait http://localhost:${HAPROXY_S_HELPERS_PORT:-65008} );then break;fi;done
      busybox ip -4 route list match 0/0 \
        | awk '{print $$3" host.docker.internal"}' >> /etc/hosts
      for i in /haproxy/*frep;do
        j="$$(basename $$(basename $$i .frep) .jfrep)"
        frep --overwrite "$$i:/$$j"
      done
      while true;do printf "HTTP/1.1 200 OK\n\nstarted"| ( busybox nc -l 127.0.0.1 -p ${HAPROXY_S_HAPROXY_PORT:-65009}||/bin/true);done&
      {% if cops_drupal_haproxy_certbot %}
      dockerize -wait http://localhost:${HAPROXY_S_CERTBOT_PORT:-65010} -timeout 180s
      {% endif %}
      exec gosu 0 haproxy -f /haproxy.cfg
{% if cops_drupal_haproxy_certbot %}
  certbot: { <<: [ *common ] }
{% endif %}
volumes:
  cops_helpers:

