# syntax=docker/dockerfile:1.3
ARG PYTHON_BASE=corpusops/python:3-slim
FROM $PYTHON_BASE
RUN apt-get update -qq
ADD docs/apt.txt ./
RUN apt-get install -qq $(cat apt.txt)
ADD docs/req*.txt ./
RUN pip install --no-cache-dir -r requirements.txt
ADD docs /code/docs
ADD local /code/local/
WORKDIR /code/docs
ENTRYPOINT ["/code/docs/entry.sh"]
