ARG BASE=corpusops/ubuntu-bare:20.04
FROM $BASE AS BASE

RUN \
    --mount=type=cache,id=cops${BASE}apt,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=cops${BASE}list,target=/var/lib/apt/lists,sharing=locked \
    bash -c 'set -ex \
    && : "Install Varnish Package" \
    && apt-get update && apt-get install -y varnish \
    '

RUN mkdir -p /docker/sys/etc/varnish/

COPY local/drupal-deploy-common/sys/varnish.sh /
COPY sys/etc/varnish/varnish.vcl.frep /docker/sys/etc/varnish/varnish.vcl.frep

WORKDIR /docker/sys

ENTRYPOINT []

CMD "/varnish.sh"
