---
# APP
- hosts: "{{drupal_servers|default('all')}}"
  roles: [corpusops.roles/ansible_plugins]
  tasks:
  - when: ["cops_drupal_lifecycle_app|default(true)"]
    tags: ["cops_drupal_lifecycle_app"]
    block:
    - include_role: {name: drupal_vars, allow_duplicates: false}
    - include_role: {name: drupal,      allow_duplicates: false}
      tags: [drupal_install]
