---
- hosts: "{{deploy_key_hosts|default('controller')}}"
  gather_facts: false
  roles: [corpusops.roles/ansible_plugins]
  tasks:
  - include_role:
      name: corpusops.roles/project/_deploy_key_teardown
