---
- hosts: "{{teleport_origin}}"
  roles: [corpusops.roles/ansible_plugins]
  tasks:
  - block:
    - include_role: {name: drupal_vars, public: y}
      tags: [backup, backup_vars]
    - block:
      - when: "teleport_debug|default(false)"
        debug: {msg: "{{teleport_paths}}"}
      - file:
          state: directory
          mode: "750"
          path: "{{teleport_paths.origin_dump}}"
      - shell: "{{teleport_origin_dump_script}}"
        name: "Make DB dump on source"
        no_log: "{{not teleport_debug|default(False)}}"
      tags: [backup, backup_db]
- hosts: "{{teleport_destination}}"
  roles: [corpusops.roles/ansible_plugins]
  tasks:
  - include_role: {name: drupal_vars, public: y}
    tags: [reset, sync, sync_vars]
  # ssh key setup for rsync over ssh transfer
  - block:
    - debug: {var: teleport_deploy_ssh_key_paths}
      register: s
    - include_role: {name: corpusops.roles/project/_deploy_key_setup}
      name: "Deploy SSH key"
      vars: {cops_deploy_ssh_key_paths: "{{s.teleport_deploy_ssh_key_paths}}"}
    tags: [reset, ssh_setup]
  # stop drupal first
  - when: "teleport_do_stop_services|default(true)"
    name: "Stopping APP services"
    shell: "{{teleport_stop_script}}"
    tags: [reset, stop_services]
  # database dump xfer
  - when: "teleport_do_sync_db|default(true)"
    tags: [reset, sync_db]
    vars: {teleport_items: "{{teleport_sync_db_files}}"}
    block:
    - include_role: {name: drupal/roles/docker_container_transfer}
      name: "XFER dump"
      tags: [reset, xfer_dumps]
    - include_role: {name: drupal/roles/docker_container_fixperms}
      name: "DB fixperms"
      tags: [reset, fixperms_db]
  # database reset from dump
  - when: "teleport_do_reset_db|default(true)"
    tags: [reset, reset_db]
    block:
    - when: "teleport_do_db_restart|default(true)"
      name: "DB restart"
      shell: "{{teleport_db_restart_script}}"
      args: {executable: /bin/bash}
      tags: [reset, db_restart]
    - when: "teleport_do_load_dump|default(true)"
      name: "Load dump"
      shell: "{{teleport_reset_db_script}}"
      args: {executable: /bin/bash}
      tags: [reset, load_dump]
  # medias transfer
  - when: "teleport_do_sync_medias|default(true)"
    vars: {teleport_items: "{{teleport_sync_files}}"}
    tags: [reset, sync_medias]
    block:
    - include_role: {name: drupal/roles/docker_container_ifexists, public: y}
      name: "XFER IFEXISTS"
      tags: [reset, xfer, xfer_ifexists]
    - include_role: {name: drupal/roles/docker_container_transfer}
      name: "XFER medias"
      tags: [reset, xfer, xfer_medias]
    - include_role: {name: drupal/roles/docker_container_fixperms}
      name: "Fixperms medias"
      tags: [reset, xfer, fixperms_medias]
  # - {when: "teleport_debug|default(false)", pause: {}}
  # post reset scripts
  - when: "teleport_post_reset|default(true)"
    tags: [reset, post_reset]
    block:
    - when: "teleport_do_post_reset_script|default(true)"
      name: "Post reset"
      shell: "{{teleport_post_reset_script}}"
      args: {executable: /bin/bash}
      tags: [reset, post_script]
    - when: "teleport_do_post_reset_restart|default(true)"
      name: "Restart services"
      shell: "{{teleport_restart_script}}"
      args: {executable: /bin/bash}
      tags: [reset, reset_restart]
